name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This action checks out your repository
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'  # Use whatever node version your project requires
      - name: Install Dependencies
        run: cd fe && yarn install  # Use the correct path to your project and the correct command to install your dependencies.
      - name: Build Project
        run: cd fe && yarn deploy  # Use the correct build command for your project. It may include 'dist' as part of the script in your package.json.
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: fe/dist # The folder the action should deploy.
          # You can specify additional configuration here as needed.